-- Postgres baseline: the devmon schema as of MSSQL migration 0025, with the DTM_ prefix dropped.
-- Until the first production deploy this file may be edited in place (no database exists yet);
-- after that, forward only.
--
-- Type mapping from the MSSQL originals:
--   INT IDENTITY -> INTEGER GENERATED BY DEFAULT AS IDENTITY; BIGINT IDENTITY likewise
--   UNIQUEIDENTIFIER DEFAULT NEWID() -> UUID DEFAULT gen_random_uuid() (built in since PG 13)
--   NVARCHAR(n) -> VARCHAR(n); NVARCHAR(MAX) -> TEXT; BIT -> BOOLEAN; TINYINT -> SMALLINT;
--   FLOAT -> DOUBLE PRECISION; VARBINARY(MAX) -> BYTEA; DATETIME2 -> TIMESTAMPTZ
--   Filtered indexes -> partial indexes.
-- SQL Server compared strings case insensitively (default CI collation). The columns where the
-- app relies on that (usernames, emails, tag names) are CITEXT, with a CHECK for the old length.
-- SQL Server unique indexes treat NULL as one value; the ones that depend on it use
-- NULLS NOT DISTINCT (needs PG 15+).
-- No literal question marks anywhere in this file: knex turns them into bind placeholders.

CREATE EXTENSION IF NOT EXISTS citext;

-- Sessions for connect-session-knex (column names and types it expects on Postgres).
CREATE TABLE sessions
(
    sid VARCHAR(255) NOT NULL PRIMARY KEY,
    sess JSON NOT NULL,
    expired TIMESTAMPTZ NOT NULL
);
CREATE INDEX ix_sessions_expired ON sessions (expired);

-- Site scope settings.
CREATE TABLE settings
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(80) NOT NULL,
    setting_value TEXT NULL,
    kind VARCHAR(10) NOT NULL,                       -- int | bool | string | secret
    description VARCHAR(500) NOT NULL,
    min_value INTEGER NULL,
    max_value INTEGER NULL,
    needs_restart BOOLEAN NOT NULL DEFAULT false,
    updated_epoch BIGINT NULL,
    updated_by INTEGER NULL,
    setting_group VARCHAR(20) NOT NULL DEFAULT 'general'   -- admin tab: general | email | sms | logging | api | mqtt
);
CREATE UNIQUE INDEX ux_settings_key ON settings (setting_key);

-- Tenancy root. mqtt_* columns are the per account read only broker user for acct/{uid}/#.
CREATE TABLE accounts
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(120) NOT NULL,
    is_enabled BOOLEAN NOT NULL DEFAULT true,
    notifications_muted BOOLEAN NOT NULL DEFAULT false,   -- account kill switch
    mqtt_enabled BOOLEAN NOT NULL DEFAULT false,
    mqtt_username VARCHAR(80) NULL,
    mqtt_password_enc VARCHAR(400) NULL,
    created_epoch BIGINT NOT NULL,
    created_by INTEGER NULL,
    delete_epoch BIGINT NULL
);
CREATE UNIQUE INDEX ux_accounts_uid ON accounts (uid);
CREATE INDEX ix_accounts_live ON accounts (name) WHERE delete_epoch IS NULL;

CREATE TABLE locations
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    account_id INTEGER NOT NULL,
    name VARCHAR(120) NOT NULL,
    iana_timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
    address VARCHAR(300) NULL,
    lat DOUBLE PRECISION NULL,
    lng DOUBLE PRECISION NULL,
    membership_mode VARCHAR(10) NOT NULL DEFAULT 'normal',   -- locked | normal | release
    notifications_muted BOOLEAN NOT NULL DEFAULT false,
    notes TEXT NULL,
    created_epoch BIGINT NOT NULL,
    created_by INTEGER NULL,
    delete_epoch BIGINT NULL,
    -- active | muted (evaluate, do not notify) | offline (do not evaluate). notifications_muted is
    -- kept in sync (muted and offline both set it).
    alarm_mode VARCHAR(8) NOT NULL DEFAULT 'active',
    CONSTRAINT fk_locations_accounts FOREIGN KEY (account_id) REFERENCES accounts (id)
);
CREATE UNIQUE INDEX ux_locations_uid ON locations (uid);
CREATE INDEX ix_locations_account_live ON locations (account_id, name) WHERE delete_epoch IS NULL;

CREATE TABLE users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    username CITEXT NOT NULL CHECK (char_length(username) <= 40),
    email CITEXT NOT NULL CHECK (char_length(email) <= 254),
    display_name VARCHAR(80) NULL,
    phone VARCHAR(30) NULL,
    password_hash VARCHAR(100) NULL,
    is_superadmin BOOLEAN NOT NULL DEFAULT false,
    must_set_password BOOLEAN NOT NULL DEFAULT false,     -- seeded/reset accounts are confined until they set one
    username_changed_epoch BIGINT NULL,
    password_changed_epoch BIGINT NULL,                   -- sessions older than this are invalid
    email_enabled BOOLEAN NOT NULL DEFAULT true,
    sms_enabled BOOLEAN NOT NULL DEFAULT false,
    email_paused_until_epoch BIGINT NULL,
    sms_paused_until_epoch BIGINT NULL,
    email_bounced BOOLEAN NOT NULL DEFAULT false,
    last_login_epoch BIGINT NULL,
    created_epoch BIGINT NOT NULL,
    created_by INTEGER NULL,
    delete_epoch BIGINT NULL
);
CREATE UNIQUE INDEX ux_users_uid ON users (uid);
CREATE UNIQUE INDEX ux_users_username ON users (username) WHERE delete_epoch IS NULL;
CREATE UNIQUE INDEX ux_users_email ON users (email) WHERE delete_epoch IS NULL;

CREATE TABLE username_history
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    old_username CITEXT NOT NULL CHECK (char_length(old_username) <= 40),
    changed_epoch BIGINT NOT NULL,
    CONSTRAINT fk_username_history_users FOREIGN KEY (user_id) REFERENCES users (id)
);

-- One grants table for users and API credentials. Bits from permissions.js.
CREATE TABLE grants
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grantee_type VARCHAR(14) NOT NULL,               -- user | api_credential
    grantee_id INTEGER NOT NULL,
    scope_type VARCHAR(8) NOT NULL,                  -- account | location
    scope_id INTEGER NOT NULL,
    permission_bits BIGINT NOT NULL,
    created_epoch BIGINT NOT NULL,
    created_by INTEGER NULL
);
CREATE UNIQUE INDEX ux_grants_scope ON grants (grantee_type, grantee_id, scope_type, scope_id);
CREATE INDEX ix_grants_scope ON grants (scope_type, scope_id);

CREATE TABLE invites
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    email CITEXT NOT NULL CHECK (char_length(email) <= 254),
    username CITEXT NOT NULL CHECK (char_length(username) <= 40),
    scope_type VARCHAR(8) NOT NULL,
    scope_id INTEGER NOT NULL,
    permission_bits BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    expires_epoch BIGINT NOT NULL,
    accepted_epoch BIGINT NULL,
    cancelled_epoch BIGINT NULL,
    created_epoch BIGINT NOT NULL,
    created_by INTEGER NOT NULL
);
CREATE UNIQUE INDEX ux_invites_uid ON invites (uid);
CREATE UNIQUE INDEX ux_invites_live_email ON invites (email) WHERE accepted_epoch IS NULL AND cancelled_epoch IS NULL;
CREATE UNIQUE INDEX ux_invites_token ON invites (token_hash);

CREATE TABLE api_credentials
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    account_id INTEGER NULL,                         -- NULL = superadmin global credential
    name VARCHAR(80) NOT NULL,
    key_prefix VARCHAR(26) NOT NULL,                 -- <API_KEY_PREFIX>_<8 hex>, up to 25 characters
    key_hash CHAR(64) NOT NULL,
    is_enabled BOOLEAN NOT NULL DEFAULT true,
    expires_epoch BIGINT NULL,
    last_used_epoch BIGINT NULL,
    created_epoch BIGINT NOT NULL,
    created_by INTEGER NOT NULL,
    delete_epoch BIGINT NULL,
    CONSTRAINT fk_api_credentials_accounts FOREIGN KEY (account_id) REFERENCES accounts (id)
);
CREATE UNIQUE INDEX ux_api_credentials_uid ON api_credentials (uid);
CREATE UNIQUE INDEX ux_api_credentials_hash ON api_credentials (key_hash);

-- Shared magic link mechanics: reset links, alarm action links, test sends.
CREATE TABLE tokens
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purpose VARCHAR(24) NOT NULL,                    -- password_reset | alarm_action | ...
    subject_type VARCHAR(16) NOT NULL,
    subject_id INTEGER NOT NULL,
    token_hash CHAR(64) NOT NULL,
    meta TEXT NULL,
    expires_epoch BIGINT NOT NULL,
    used_epoch BIGINT NULL,
    created_epoch BIGINT NOT NULL
);
CREATE UNIQUE INDEX ux_tokens_hash ON tokens (token_hash);
CREATE INDEX ix_tokens_subject ON tokens (purpose, subject_type, subject_id);

-- Shadow of deviceTypes/*.js; upserted at boot, never edited by hand.
CREATE TABLE device_types
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(40) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    kind VARCHAR(8) NOT NULL,                        -- gateway | node | beacon | direct | asset
    dedup_mode VARCHAR(8) NOT NULL,                  -- counter | window | none
    min_interval_secs INTEGER NOT NULL DEFAULT 0,
    models VARCHAR(400) NULL                         -- comma list of model names mapping to this type
);
CREATE UNIQUE INDEX ux_device_types_slug ON device_types (slug);

-- A device row is one placement of a unit at one location. hardware_id identifies the hardware
-- (MAC, host name, IMEI); NULL for assets.
CREATE TABLE devices
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    location_id INTEGER NOT NULL,
    device_type_id INTEGER NOT NULL,
    kind VARCHAR(8) NOT NULL,                        -- denormalized from the type for list splits
    name VARCHAR(120) NOT NULL,
    hardware_id VARCHAR(255) NULL,
    model VARCHAR(40) NULL,
    firmware VARCHAR(24) NULL,
    is_offline BOOLEAN NOT NULL DEFAULT false,
    is_archived BOOLEAN NOT NULL DEFAULT false,
    last_seen_epoch BIGINT NULL,
    joined_epoch BIGINT NULL,
    last_heard_by INTEGER NULL,                      -- self reference; a direct device points at itself
    notes TEXT NULL,
    created_epoch BIGINT NOT NULL,
    created_by INTEGER NULL,
    delete_epoch BIGINT NULL,
    battery_chemistry VARCHAR(24) NULL,              -- NULL = the device type's batteryChemistry default
    CONSTRAINT fk_devices_locations FOREIGN KEY (location_id) REFERENCES locations (id),
    CONSTRAINT fk_devices_device_types FOREIGN KEY (device_type_id) REFERENCES device_types (id),
    CONSTRAINT fk_devices_heard_by FOREIGN KEY (last_heard_by) REFERENCES devices (id)
);
CREATE UNIQUE INDEX ux_devices_uid ON devices (uid);
-- Unique among live, unarchived devices; archived rows keep theirs for history.
CREATE UNIQUE INDEX ux_devices_hardware_id ON devices (hardware_id) WHERE delete_epoch IS NULL AND is_archived = false AND hardware_id IS NOT NULL;
CREATE INDEX ix_devices_location_live ON devices (location_id, kind) WHERE delete_epoch IS NULL;

-- MQTT identity of the physical unit, keyed by MAC; lives across placements. device_id is from the
-- old 1:1 model and nothing new writes it.
CREATE TABLE device_credentials
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NULL,
    mac CHAR(12) NOT NULL,
    state VARCHAR(8) NOT NULL DEFAULT 'pending',     -- pending | active
    broker_username VARCHAR(80) NOT NULL,            -- the unit GUID, lower case
    broker_password_enc VARCHAR(400) NULL,           -- NULL under the static broker driver
    created_epoch BIGINT NOT NULL,
    rotated_epoch BIGINT NULL,
    activated_epoch BIGINT NULL,
    delete_epoch BIGINT NULL,
    broker_fault VARCHAR(300) NULL,                  -- daily broker audit result; NULL = nothing wrong
    broker_checked_epoch BIGINT NULL,
    type_slug VARCHAR(40) NULL,                      -- device type declared at provisioning
    mqtt_seen_epoch BIGINT NULL,                     -- first MQTT message from the unit
    CONSTRAINT fk_device_credentials_devices FOREIGN KEY (device_id) REFERENCES devices (id)
);
CREATE UNIQUE INDEX ux_device_credentials_mac ON device_credentials (mac) WHERE delete_epoch IS NULL;
CREATE UNIQUE INDEX ux_device_credentials_broker_username ON device_credentials (broker_username) WHERE delete_epoch IS NULL;

-- Permanent birth record. Never deleted.
CREATE TABLE device_registry
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mac CHAR(12) NOT NULL,
    first_model VARCHAR(40) NULL,
    first_firmware VARCHAR(24) NULL,
    first_heard_epoch BIGINT NOT NULL,
    first_heard_via VARCHAR(16) NOT NULL,            -- provision | join | frame | ble | manual
    last_firmware VARCHAR(24) NULL,
    last_heard_epoch BIGINT NOT NULL,
    last_device_uid UUID NULL
);
CREATE UNIQUE INDEX ux_device_registry_mac ON device_registry (mac);

-- Which gateways hear which device; upserted on every frame including dedup losers.
CREATE TABLE device_coverage
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NOT NULL,
    gateway_id INTEGER NOT NULL,
    last_heard_epoch BIGINT NOT NULL,
    last_rssi SMALLINT NULL,
    CONSTRAINT fk_device_coverage_devices FOREIGN KEY (device_id) REFERENCES devices (id),
    CONSTRAINT fk_device_coverage_gateways FOREIGN KEY (gateway_id) REFERENCES devices (id)
);
CREATE UNIQUE INDEX ux_device_coverage_pair ON device_coverage (device_id, gateway_id);
CREATE INDEX ix_device_coverage_gateway ON device_coverage (gateway_id, last_heard_epoch);

CREATE TABLE sensors
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    device_id INTEGER NOT NULL,
    channel_id VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    metric VARCHAR(40) NOT NULL,                     -- metrics/<slug>.js
    is_derived BOOLEAN NOT NULL DEFAULT false,
    display_unit VARCHAR(16) NULL,                   -- NULL = inherit
    display_precision SMALLINT NULL,                 -- NULL = inherit
    retention_days INTEGER NULL,                     -- NULL = inherit, -1 = forever
    formula_slug VARCHAR(40) NULL,
    formula_params TEXT NULL,
    formula_inputs TEXT NULL,                        -- JSON array of sensor uids
    carried_state TEXT NULL,
    last_value DOUBLE PRECISION NULL,
    last_epoch BIGINT NULL,
    last_reading_id BIGINT NULL,                     -- no FK: the reading may be purged
    is_enabled BOOLEAN NOT NULL DEFAULT true,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_epoch BIGINT NOT NULL,
    delete_epoch BIGINT NULL,
    description TEXT NULL,                           -- NULL = the device type channel's description
    is_hidden BOOLEAN NOT NULL DEFAULT false,        -- stores readings, no alarms, left out of lists
    CONSTRAINT fk_sensors_devices FOREIGN KEY (device_id) REFERENCES devices (id)
);
CREATE UNIQUE INDEX ux_sensors_uid ON sensors (uid);
CREATE UNIQUE INDEX ux_sensors_channel ON sensors (device_id, channel_id) WHERE delete_epoch IS NULL;

-- Pure time series: serial id only, canonical units only, retention by window.
CREATE TABLE readings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id INTEGER NOT NULL,
    epoch BIGINT NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    gateway_id INTEGER NULL,
    rssi SMALLINT NULL
);
CREATE INDEX ix_readings_sensor_epoch ON readings (sensor_id, epoch);

-- Cross gateway dedup arbiter: the unique index is the claim.
CREATE TABLE device_frames
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NOT NULL,
    frame_counter BIGINT NOT NULL,
    epoch BIGINT NOT NULL
);
CREATE UNIQUE INDEX ux_device_frames ON device_frames (device_id, frame_counter);
CREATE INDEX ix_device_frames_epoch ON device_frames (epoch);

-- Optional raw capture for parser debugging, RAW_PUBLISH_LOG_DAYS > 0.
CREATE TABLE raw_publish_log
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epoch BIGINT NOT NULL,
    topic VARCHAR(200) NOT NULL,
    payload BYTEA NOT NULL
);
CREATE INDEX ix_raw_publish_log_epoch ON raw_publish_log (epoch);

-- Asset slots bound to real sensors in the same location.
CREATE TABLE asset_inputs
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_device_id INTEGER NOT NULL,
    slot VARCHAR(40) NOT NULL,
    source_sensor_id INTEGER NULL,
    is_broken BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT fk_asset_inputs_devices FOREIGN KEY (asset_device_id) REFERENCES devices (id),
    CONSTRAINT fk_asset_inputs_sensors FOREIGN KEY (source_sensor_id) REFERENCES sensors (id)
);
CREATE UNIQUE INDEX ux_asset_inputs_slot ON asset_inputs (asset_device_id, slot);

CREATE TABLE account_settings
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL,
    setting_key VARCHAR(80) NOT NULL,
    setting_value TEXT NULL,
    updated_epoch BIGINT NOT NULL,
    updated_by INTEGER NULL,
    CONSTRAINT fk_account_settings_accounts FOREIGN KEY (account_id) REFERENCES accounts (id)
);
CREATE UNIQUE INDEX ux_account_settings_key ON account_settings (account_id, setting_key);

CREATE TABLE location_settings
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id INTEGER NOT NULL,
    setting_key VARCHAR(80) NOT NULL,
    setting_value TEXT NULL,
    updated_epoch BIGINT NOT NULL,
    updated_by INTEGER NULL,
    CONSTRAINT fk_location_settings_locations FOREIGN KEY (location_id) REFERENCES locations (id)
);
CREATE UNIQUE INDEX ux_location_settings_key ON location_settings (location_id, setting_key);

-- Lists inherit downward with merge; a child may hide an inherited item, not edit it.
-- scope_id is NULL for site scope, so the unique index needs NULLS NOT DISTINCT.
CREATE TABLE lists
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(40) NOT NULL,
    scope_type VARCHAR(8) NOT NULL,                  -- site | account | location
    scope_id INTEGER NULL,
    display_name VARCHAR(80) NOT NULL,
    order_mode VARCHAR(12) NOT NULL DEFAULT 'entered'   -- entered | alphabetical | manual
);
CREATE UNIQUE INDEX ux_lists_scope ON lists (slug, scope_type, scope_id) NULLS NOT DISTINCT;

CREATE TABLE list_items
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_id INTEGER NOT NULL,
    label VARCHAR(120) NOT NULL,
    value VARCHAR(120) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    meta TEXT NULL,                                  -- e.g. {"apply_tags":["dashboard"]}
    CONSTRAINT fk_list_items_lists FOREIGN KEY (list_id) REFERENCES lists (id)
);
CREATE INDEX ix_list_items_list ON list_items (list_id, sort_order);

CREATE TABLE list_item_hides
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_item_id INTEGER NOT NULL,
    scope_type VARCHAR(8) NOT NULL,
    scope_id INTEGER NOT NULL,
    CONSTRAINT fk_list_item_hides_items FOREIGN KEY (list_item_id) REFERENCES list_items (id)
);
CREATE UNIQUE INDEX ux_list_item_hides ON list_item_hides (list_item_id, scope_type, scope_id);

CREATE TABLE tags
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL,
    name CITEXT NOT NULL CHECK (char_length(name) <= 40),
    is_known BOOLEAN NOT NULL DEFAULT false,         -- seeded from code (dashboard, dailyReport)
    CONSTRAINT fk_tags_accounts FOREIGN KEY (account_id) REFERENCES accounts (id)
);
CREATE UNIQUE INDEX ux_tags_name ON tags (account_id, name);

CREATE TABLE taggings
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id INTEGER NOT NULL,
    entity_type VARCHAR(10) NOT NULL,                -- device | sensor | location
    entity_id INTEGER NOT NULL,
    CONSTRAINT fk_taggings_tags FOREIGN KEY (tag_id) REFERENCES tags (id)
);
CREATE UNIQUE INDEX ux_taggings ON taggings (tag_id, entity_type, entity_id);
CREATE INDEX ix_taggings_entity ON taggings (entity_type, entity_id);

-- A sensor can opt out of a tag it would inherit from its device. Kept apart from taggings so a
-- reader that ignores exclusions falls back to plain inheritance.
CREATE TABLE tag_exclusions
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id INTEGER NOT NULL,
    entity_type VARCHAR(10) NOT NULL,                -- sensor
    entity_id INTEGER NOT NULL,
    CONSTRAINT fk_tag_exclusions_tags FOREIGN KEY (tag_id) REFERENCES tags (id)
);
CREATE UNIQUE INDEX ux_tag_exclusions ON tag_exclusions (tag_id, entity_type, entity_id);
CREATE INDEX ix_tag_exclusions_entity ON tag_exclusions (entity_type, entity_id);

CREATE TABLE contacts
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    account_id INTEGER NOT NULL,
    location_id INTEGER NULL,                        -- NULL = usable everywhere in the account
    name VARCHAR(80) NOT NULL,
    email CITEXT NULL CHECK (char_length(email) <= 254),
    phone VARCHAR(30) NULL,
    sms_opted_out BOOLEAN NOT NULL DEFAULT false,
    created_epoch BIGINT NOT NULL,
    delete_epoch BIGINT NULL,
    CONSTRAINT fk_contacts_accounts FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_contacts_locations FOREIGN KEY (location_id) REFERENCES locations (id)
);
CREATE UNIQUE INDEX ux_contacts_uid ON contacts (uid);

-- Escalation ladders are the only notification path.
CREATE TABLE alert_groups
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    account_id INTEGER NOT NULL,
    name VARCHAR(80) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT false,
    tag_query TEXT NULL,                             -- {any,all,none,text}; NULL = explicit attachment only
    created_epoch BIGINT NOT NULL,
    delete_epoch BIGINT NULL,
    CONSTRAINT fk_alert_groups_accounts FOREIGN KEY (account_id) REFERENCES accounts (id)
);
CREATE UNIQUE INDEX ux_alert_groups_uid ON alert_groups (uid);

CREATE TABLE alert_group_levels
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_group_id INTEGER NOT NULL,
    level_no SMALLINT NOT NULL,
    wait_minutes INTEGER NOT NULL DEFAULT 0,         -- delay before this level after the previous one
    CONSTRAINT fk_alert_group_levels_groups FOREIGN KEY (alert_group_id) REFERENCES alert_groups (id)
);
CREATE UNIQUE INDEX ux_alert_group_levels ON alert_group_levels (alert_group_id, level_no);

CREATE TABLE alert_group_recipients
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_id INTEGER NOT NULL,
    recipient_type VARCHAR(12) NOT NULL,             -- user | contact | all_access
    recipient_id INTEGER NULL,
    CONSTRAINT fk_alert_group_recipients_levels FOREIGN KEY (level_id) REFERENCES alert_group_levels (id)
);
CREATE INDEX ix_alert_group_recipients_level ON alert_group_recipients (level_id);

-- Threshold rules and no_data rules share a table; threshold columns are NULL for no_data.
CREATE TABLE alarm_rules
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    sensor_id INTEGER NOT NULL,
    rule_kind VARCHAR(10) NOT NULL,                  -- threshold | no_data
    direction VARCHAR(5) NULL,                       -- upper | lower
    threshold DOUBLE PRECISION NULL,                 -- canonical units
    severity VARCHAR(10) NOT NULL DEFAULT 'alarm',   -- info | warning | alarm | emergency
    exceed_secs INTEGER NOT NULL DEFAULT 0,
    return_secs INTEGER NOT NULL DEFAULT 0,
    timeout_secs INTEGER NULL,                       -- no_data only
    is_enabled BOOLEAN NOT NULL DEFAULT true,
    use_default_group BOOLEAN NOT NULL DEFAULT true,
    channel_policy VARCHAR(400) NULL,                -- per transition x channel JSON; NULL = all on
    breach_since BIGINT NULL,
    return_since BIGINT NULL,
    created_epoch BIGINT NOT NULL,
    delete_epoch BIGINT NULL,
    CONSTRAINT fk_alarm_rules_sensors FOREIGN KEY (sensor_id) REFERENCES sensors (id)
);
CREATE UNIQUE INDEX ux_alarm_rules_uid ON alarm_rules (uid);
CREATE INDEX ix_alarm_rules_sensor_live ON alarm_rules (sensor_id) WHERE delete_epoch IS NULL;

CREATE TABLE alarm_rule_alert_groups
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alarm_rule_id INTEGER NOT NULL,
    alert_group_id INTEGER NOT NULL,
    CONSTRAINT fk_alarm_rule_alert_groups_rules FOREIGN KEY (alarm_rule_id) REFERENCES alarm_rules (id),
    CONSTRAINT fk_alarm_rule_alert_groups_groups FOREIGN KEY (alert_group_id) REFERENCES alert_groups (id)
);
CREATE UNIQUE INDEX ux_alarm_rule_alert_groups ON alarm_rule_alert_groups (alarm_rule_id, alert_group_id);

-- One active alarm per sensor per direction; cleared rows stay as history.
CREATE TABLE alarms
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    sensor_id INTEGER NOT NULL,
    direction VARCHAR(7) NOT NULL,                   -- upper | lower | no_data
    severity VARCHAR(10) NOT NULL,
    rule_id INTEGER NULL,                            -- rule that set the current severity
    raised_epoch BIGINT NOT NULL,
    cleared_epoch BIGINT NULL,
    clear_reason VARCHAR(40) NULL,                   -- returned | manual | offline | disarmed | archived
    acked_by INTEGER NULL,
    acked_epoch BIGINT NULL,
    ack_until_epoch BIGINT NULL,
    last_notified_epoch BIGINT NULL,
    suppressed_by INTEGER NULL,                      -- gateway alarm id
    trigger_value DOUBLE PRECISION NULL,
    CONSTRAINT fk_alarms_sensors FOREIGN KEY (sensor_id) REFERENCES sensors (id)
);
CREATE UNIQUE INDEX ux_alarms_uid ON alarms (uid);
CREATE UNIQUE INDEX ux_alarms_active ON alarms (sensor_id, direction) WHERE cleared_epoch IS NULL;
CREATE INDEX ix_alarms_sensor_history ON alarms (sensor_id, raised_epoch);

CREATE TABLE alarm_events
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alarm_id INTEGER NOT NULL,
    epoch BIGINT NOT NULL,
    event_kind VARCHAR(14) NOT NULL,                 -- raised | escalated | de_escalated | acknowledged | ignored | cleared | re_notified | suppressed
    severity VARCHAR(10) NULL,
    value DOUBLE PRECISION NULL,
    actor_type VARCHAR(14) NULL,                     -- user | api_credential | system
    actor_id INTEGER NULL,
    comment VARCHAR(500) NULL,
    CONSTRAINT fk_alarm_events_alarms FOREIGN KEY (alarm_id) REFERENCES alarms (id)
);
CREATE INDEX ix_alarm_events_alarm ON alarm_events (alarm_id, epoch);

CREATE TABLE alarm_escalations
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alarm_id INTEGER NOT NULL,
    alert_group_id INTEGER NOT NULL,
    current_level SMALLINT NOT NULL DEFAULT 1,
    level_entered_epoch BIGINT NOT NULL,
    is_stopped BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT fk_alarm_escalations_alarms FOREIGN KEY (alarm_id) REFERENCES alarms (id),
    CONSTRAINT fk_alarm_escalations_groups FOREIGN KEY (alert_group_id) REFERENCES alert_groups (id)
);
CREATE UNIQUE INDEX ux_alarm_escalations ON alarm_escalations (alarm_id, alert_group_id);

-- Recurring disarm windows, evaluated in the location timezone.
CREATE TABLE alarm_schedules
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    account_id INTEGER NOT NULL,
    name VARCHAR(80) NOT NULL,
    dow_mask SMALLINT NOT NULL,                      -- bit 0 = Sunday
    start_minute SMALLINT NOT NULL,
    end_minute SMALLINT NOT NULL,                    -- end < start crosses midnight
    created_epoch BIGINT NOT NULL,
    delete_epoch BIGINT NULL,
    CONSTRAINT fk_alarm_schedules_accounts FOREIGN KEY (account_id) REFERENCES accounts (id)
);
CREATE UNIQUE INDEX ux_alarm_schedules_uid ON alarm_schedules (uid);

CREATE TABLE alarm_schedule_links
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id INTEGER NOT NULL,
    entity_type VARCHAR(6) NOT NULL,                 -- device | rule
    entity_id INTEGER NOT NULL,
    CONSTRAINT fk_alarm_schedule_links_schedules FOREIGN KEY (schedule_id) REFERENCES alarm_schedules (id)
);
CREATE UNIQUE INDEX ux_alarm_schedule_links ON alarm_schedule_links (schedule_id, entity_type, entity_id);

CREATE TABLE offline_periods
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NOT NULL,
    start_epoch BIGINT NOT NULL,
    end_epoch BIGINT NULL,                           -- NULL = open ended
    reason VARCHAR(120) NOT NULL,
    comment VARCHAR(500) NOT NULL,
    created_by INTEGER NOT NULL,
    created_epoch BIGINT NOT NULL,
    CONSTRAINT fk_offline_periods_devices FOREIGN KEY (device_id) REFERENCES devices (id)
);
CREATE INDEX ix_offline_periods_device ON offline_periods (device_id, start_epoch);

-- Every send decision writes here first; "why didn't I get it" is a query.
CREATE TABLE notifications
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epoch BIGINT NOT NULL,
    kind VARCHAR(16) NOT NULL,                       -- alarm | invite | reset | report | test | system
    channel VARCHAR(5) NOT NULL,                     -- email | sms
    recipient_type VARCHAR(8) NOT NULL,              -- user | contact | address
    recipient_id INTEGER NULL,
    address VARCHAR(254) NOT NULL,
    alarm_event_id INTEGER NULL,
    report_run_id INTEGER NULL,
    ladder_note VARCHAR(80) NULL,                    -- "level 2 of Night crew"
    outcome VARCHAR(10) NOT NULL,                    -- sent | failed | suppressed
    reason VARCHAR(200) NULL,
    provider VARCHAR(16) NULL,
    provider_message_id VARCHAR(120) NULL,
    subject VARCHAR(200) NULL,
    body TEXT NULL,                                  -- full message, for the detail view
    provider_response TEXT NULL,
    sender VARCHAR(254) NULL
);
CREATE INDEX ix_notifications_epoch ON notifications (epoch);
CREATE INDEX ix_notifications_alarm_event ON notifications (alarm_event_id);
CREATE INDEX ix_notifications_recipient ON notifications (recipient_type, recipient_id, epoch);

-- scope_id is NULL for global scope, so the unique index needs NULLS NOT DISTINCT.
CREATE TABLE user_notification_prefs
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    scope_type VARCHAR(8) NOT NULL,                  -- global | account | location
    scope_id INTEGER NULL,
    channel VARCHAR(5) NOT NULL,
    enabled VARCHAR(7) NOT NULL DEFAULT 'inherit',   -- on | off | inherit
    min_severity_raise VARCHAR(10) NULL,
    min_severity_clear VARCHAR(10) NULL,
    tag_query TEXT NULL,
    CONSTRAINT fk_user_notification_prefs_users FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE UNIQUE INDEX ux_user_notification_prefs ON user_notification_prefs (user_id, scope_type, scope_id, channel) NULLS NOT DISTINCT;

CREATE TABLE activity_log
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epoch BIGINT NOT NULL,
    actor_type VARCHAR(14) NULL,                     -- user | api_credential | anonymous
    actor_id INTEGER NULL,
    actor_name VARCHAR(80) NULL,
    action VARCHAR(40) NOT NULL,
    entity_type VARCHAR(16) NULL,
    entity_uid UUID NULL,
    ip VARCHAR(45) NULL,
    user_agent VARCHAR(300) NULL,
    outcome VARCHAR(10) NOT NULL DEFAULT 'ok',       -- ok | denied | failed
    detail VARCHAR(500) NULL
);
CREATE INDEX ix_activity_log_epoch ON activity_log (epoch);
CREATE INDEX ix_activity_log_login ON activity_log (action, actor_name, epoch);
CREATE INDEX ix_activity_log_ip ON activity_log (action, ip, epoch);

-- Permanent, append only.
CREATE TABLE audit_log
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epoch BIGINT NOT NULL,
    entity_type VARCHAR(16) NOT NULL,
    entity_uid UUID NOT NULL,
    entity_name VARCHAR(120) NULL,
    field VARCHAR(60) NOT NULL,
    old_value TEXT NULL,
    new_value TEXT NULL,
    actor_type VARCHAR(14) NOT NULL,
    actor_id INTEGER NULL,
    actor_name VARCHAR(80) NULL
);
CREATE INDEX ix_audit_log_entity ON audit_log (entity_type, entity_uid, epoch);

CREATE TABLE webhooks
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    account_id INTEGER NOT NULL,
    name VARCHAR(80) NOT NULL,
    url VARCHAR(500) NOT NULL,
    signing_secret_enc VARCHAR(400) NOT NULL,
    event_types VARCHAR(400) NOT NULL,               -- comma list: reading, alarm, status
    is_enabled BOOLEAN NOT NULL DEFAULT true,
    created_epoch BIGINT NOT NULL,
    delete_epoch BIGINT NULL,
    CONSTRAINT fk_webhooks_accounts FOREIGN KEY (account_id) REFERENCES accounts (id)
);
CREATE UNIQUE INDEX ux_webhooks_uid ON webhooks (uid);

CREATE TABLE webhook_deliveries
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    webhook_id INTEGER NOT NULL,
    epoch BIGINT NOT NULL,
    event_type VARCHAR(16) NOT NULL,
    payload TEXT NOT NULL,
    attempts SMALLINT NOT NULL DEFAULT 0,
    next_attempt_epoch BIGINT NULL,
    status_code SMALLINT NULL,
    outcome VARCHAR(10) NOT NULL DEFAULT 'pending',  -- pending | sent | failed
    CONSTRAINT fk_webhook_deliveries_webhooks FOREIGN KEY (webhook_id) REFERENCES webhooks (id)
);
CREATE INDEX ix_webhook_deliveries_pending ON webhook_deliveries (next_attempt_epoch) WHERE outcome = 'pending';

-- A chart is one JSON object; a dashboard is a collection of charts and/or tag queries.
CREATE TABLE charts
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    account_id INTEGER NOT NULL,
    owner_user_id INTEGER NOT NULL,
    name VARCHAR(120) NOT NULL,
    visibility VARCHAR(12) NOT NULL DEFAULT 'private',   -- private | account_view | account_edit
    definition_json TEXT NOT NULL,
    created_epoch BIGINT NOT NULL,
    updated_epoch BIGINT NOT NULL,
    delete_epoch BIGINT NULL,
    CONSTRAINT fk_charts_accounts FOREIGN KEY (account_id) REFERENCES accounts (id)
);
CREATE UNIQUE INDEX ux_charts_uid ON charts (uid);

CREATE TABLE dashboards
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    account_id INTEGER NOT NULL,
    owner_user_id INTEGER NOT NULL,
    name VARCHAR(120) NOT NULL,
    visibility VARCHAR(12) NOT NULL DEFAULT 'private',
    tabs TEXT NOT NULL,                              -- [{name, chart_uid | tag_query}]
    created_epoch BIGINT NOT NULL,
    updated_epoch BIGINT NOT NULL,
    delete_epoch BIGINT NULL,
    CONSTRAINT fk_dashboards_accounts FOREIGN KEY (account_id) REFERENCES accounts (id)
);
CREATE UNIQUE INDEX ux_dashboards_uid ON dashboards (uid);

CREATE TABLE reports
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    account_id INTEGER NOT NULL,
    location_id INTEGER NULL,
    owner_user_id INTEGER NOT NULL,
    name VARCHAR(120) NOT NULL,
    report_type VARCHAR(40) NOT NULL,                -- reportTypes/<slug>.js
    query_json TEXT NOT NULL,
    options_json TEXT NULL,
    schedule_json VARCHAR(400) NULL,                 -- {mode, time, days}; NULL = manual only
    output_kind VARCHAR(12) NOT NULL DEFAULT 'html', -- html | csv | xlsx
    visibility VARCHAR(12) NOT NULL DEFAULT 'private',
    is_enabled BOOLEAN NOT NULL DEFAULT true,
    last_run_epoch BIGINT NULL,
    created_epoch BIGINT NOT NULL,
    delete_epoch BIGINT NULL,
    CONSTRAINT fk_reports_accounts FOREIGN KEY (account_id) REFERENCES accounts (id)
);
CREATE UNIQUE INDEX ux_reports_uid ON reports (uid);

CREATE TABLE report_recipients
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id INTEGER NOT NULL,
    recipient_type VARCHAR(8) NOT NULL,              -- user | contact
    recipient_id INTEGER NOT NULL,
    CONSTRAINT fk_report_recipients_reports FOREIGN KEY (report_id) REFERENCES reports (id)
);
CREATE UNIQUE INDEX ux_report_recipients ON report_recipients (report_id, recipient_type, recipient_id);

CREATE TABLE report_runs
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id INTEGER NOT NULL,
    epoch BIGINT NOT NULL,
    trigger_kind VARCHAR(8) NOT NULL,                -- schedule | manual
    outcome VARCHAR(10) NOT NULL,                    -- ok | failed
    row_count INTEGER NULL,
    file_path VARCHAR(300) NULL,
    error VARCHAR(500) NULL,
    CONSTRAINT fk_report_runs_reports FOREIGN KEY (report_id) REFERENCES reports (id)
);
CREATE INDEX ix_report_runs_report ON report_runs (report_id, epoch);

-- Gateway configuration, one row per unit (MAC) and config key; follows the unit across placements.
--   reported_*  what the unit last published on dev/{guid}/config/{key}
--   desired_*   a write from the config page not yet confirmed by the unit; NULL = nothing pending
--   sent_epoch  when the write was last published; ingest re-sends pending keys on connect
CREATE TABLE unit_config
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mac CHAR(12) NOT NULL,
    config_key VARCHAR(64) NOT NULL,
    reported_value VARCHAR(255) NULL,
    reported_epoch BIGINT NULL,
    desired_value VARCHAR(255) NULL,
    desired_epoch BIGINT NULL,
    desired_by INTEGER NULL,
    sent_epoch BIGINT NULL
);
CREATE UNIQUE INDEX ux_unit_config_key ON unit_config (mac, config_key);

-- Gateways hearing a MAC that is on no live device, one row per MAC and gateway placement.
CREATE TABLE unclaimed_heard
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mac CHAR(12) NOT NULL,
    gateway_id INTEGER NOT NULL,
    last_heard_epoch BIGINT NOT NULL,
    last_rssi SMALLINT NULL,
    CONSTRAINT fk_unclaimed_heard_gateways FOREIGN KEY (gateway_id) REFERENCES devices (id)
);
CREATE UNIQUE INDEX ux_unclaimed_heard_pair ON unclaimed_heard (mac, gateway_id);
CREATE INDEX ix_unclaimed_heard_gateway ON unclaimed_heard (gateway_id, last_heard_epoch);

-- Ignored unclaimed devices. account_id set hides the MAC for that account only; NULL is a
-- superadmin ignore. At most one superadmin ignore and one per account for each MAC, so the
-- unique index needs NULLS NOT DISTINCT.
CREATE TABLE unclaimed_ignored
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NULL,
    mac CHAR(12) NOT NULL,
    ignored_by INTEGER NULL,
    ignored_epoch BIGINT NOT NULL,
    CONSTRAINT fk_unclaimed_ignored_accounts FOREIGN KEY (account_id) REFERENCES accounts (id)
);
CREATE UNIQUE INDEX ux_unclaimed_ignored_scope ON unclaimed_ignored (account_id, mac) NULLS NOT DISTINCT;
CREATE INDEX ix_unclaimed_ignored_mac ON unclaimed_ignored (mac);
