-- Event log (DECISIONS.md "Event log"), replacing activity_log. One row when a request starts and
-- one when it ends, plus the events handlers, jobs and device requests record, all rows of one
-- request sharing correlation_id (the request's req.id). Columns hold what the viewer filters on;
-- everything else is in details. time is epoch milliseconds: sort by time, with id as the
-- tiebreaker (inserts are not awaited, so id order can differ from event order). No foreign keys:
-- a log row outlives the user, key or account it names. Purged after EVENT_LOG_DAYS.
CREATE TABLE event_log
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time BIGINT NOT NULL,
    user_id INTEGER NULL,
    api_credential_id INTEGER NULL,
    account_id INTEGER NULL,
    channel VARCHAR(20) NULL,                        -- web | ajax | api | device | job | mqtt
    event VARCHAR(50) NOT NULL,                      -- request, request_end, then handler events
    correlation_id VARCHAR(24) NULL,
    details JSONB NULL
);
CREATE INDEX ix_event_log_time ON event_log (time);
CREATE INDEX ix_event_log_user_time ON event_log (user_id, time);
CREATE INDEX ix_event_log_api_credential_time ON event_log (api_credential_id, time);
CREATE INDEX ix_event_log_account_time ON event_log (account_id, time);
-- Also serves the login lockout and command cooldown lookups (event plus a short time window,
-- then a details->> filter on the few rows left).
CREATE INDEX ix_event_log_event_time ON event_log (event, time);
CREATE INDEX ix_event_log_correlation ON event_log (correlation_id);

-- Nothing in activity_log is carried over: the database holds no real data yet (Sep 2026).
DROP TABLE activity_log;

-- The retention setting follows the table, keeping its value; the seed then refreshes its
-- description. If a newer seed already created EVENT_LOG_DAYS (seed run before migrate), that row
-- wins and the old one goes, instead of the rename hitting ux_settings_key.
UPDATE settings SET setting_key = 'EVENT_LOG_DAYS'
WHERE setting_key = 'ACTIVITY_LOG_DAYS'
  AND NOT EXISTS (SELECT 1 FROM settings WHERE setting_key = 'EVENT_LOG_DAYS');
DELETE FROM settings WHERE setting_key = 'ACTIVITY_LOG_DAYS';
