-- Support requests (DECISIONS.md "Support requests"): one conversation per request, reached by its
-- uid, visible to its requester and to superadmins only. Every reply is typed in the app; email
-- only tells people there is something to read.
--   status: open     needs a support answer (new, or the requester replied); counted by the badge
--           waiting  support answered, waiting on the requester
--           closed   closed by support; a requester reply reopens it
CREATE TABLE support_requests
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id INTEGER NOT NULL,                        -- the requester
    account_id INTEGER NULL,                         -- the account it is about, if the requester chose one
    subject VARCHAR(150) NOT NULL,
    status VARCHAR(8) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'waiting', 'closed')),
    created_epoch BIGINT NOT NULL,
    updated_epoch BIGINT NOT NULL,                   -- last message or status change
    closed_epoch BIGINT NULL,
    CONSTRAINT fk_support_requests_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_support_requests_accounts FOREIGN KEY (account_id) REFERENCES accounts (id)
);
CREATE UNIQUE INDEX ux_support_requests_uid ON support_requests (uid);
CREATE INDEX ix_support_requests_status ON support_requests (status, updated_epoch);
CREATE INDEX ix_support_requests_user ON support_requests (user_id, updated_epoch);

CREATE TABLE support_messages
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,                        -- the author
    from_support BOOLEAN NOT NULL,                   -- written by a superadmin answering, not the requester
    body TEXT NOT NULL CHECK (char_length(body) <= 10000),
    epoch BIGINT NOT NULL,
    CONSTRAINT fk_support_messages_requests FOREIGN KEY (request_id) REFERENCES support_requests (id),
    CONSTRAINT fk_support_messages_users FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX ix_support_messages_request ON support_messages (request_id, epoch);
