-- Queued commands (DECISIONS.md "Queued commands", pod-protocol.md section 5). Every command to a
-- pod, or through a controller to its target pods, waits here until the pod acks it.
--   device_id         the pod the message is published to (dev/{guid}/cmd/q): a controller or
--                     account pod, never a target pod
--   target            NULL: that pod itself; a MAC: one of its target pods; 'all': every one of them
--   target_device_id  the target pod's placement, for its page (NULL unless target is a MAC)
--   status: queued  waiting its turn (one command in flight per pod)
--           sent    published, waiting for the ack; sent again with the same cmd_id on reconnect
--           done    acked ok
--           failed  acked with ok false; result holds the error and per target results
-- Cancelling deletes the row. Finished rows are purged after 30 days (jobs/tasks/purge.js).
CREATE TABLE command_queue
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cmd_id UUID NOT NULL DEFAULT gen_random_uuid(),   -- the id in the message and its ack
    device_id INTEGER NOT NULL,
    target VARCHAR(12) NULL,
    target_device_id INTEGER NULL,
    cmd VARCHAR(40) NOT NULL,
    value TEXT NULL,                                  -- sent as is: a string, or JSON for set_config
    status VARCHAR(8) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'sent', 'done', 'failed')),
    created_epoch BIGINT NOT NULL,
    created_by INTEGER NULL,
    sent_epoch BIGINT NULL,
    sent_count INTEGER NOT NULL DEFAULT 0,
    done_epoch BIGINT NULL,
    result JSONB NULL,                                -- the ack: { ok, results?, error? }
    CONSTRAINT fk_command_queue_devices FOREIGN KEY (device_id) REFERENCES devices (id),
    CONSTRAINT fk_command_queue_target FOREIGN KEY (target_device_id) REFERENCES devices (id),
    CONSTRAINT fk_command_queue_users FOREIGN KEY (created_by) REFERENCES users (id)
);
CREATE UNIQUE INDEX ux_command_queue_cmd_id ON command_queue (cmd_id);
CREATE INDEX ix_command_queue_pending ON command_queue (device_id, id) WHERE status IN ('queued', 'sent');
CREATE INDEX ix_command_queue_device ON command_queue (device_id, created_epoch);
CREATE INDEX ix_command_queue_target ON command_queue (target_device_id, created_epoch) WHERE target_device_id IS NOT NULL;
CREATE INDEX ix_command_queue_finished ON command_queue (done_epoch) WHERE done_epoch IS NOT NULL;
