-- Athletes and wristbands (DECISIONS.md "Athletes and wristbands", pod-protocol.md section 8).
--
-- athletes: a person who trains. slug is the short id made from the name, unique across the whole
-- site because athletes can move between accounts; account_id is the home account, which decides
-- who can see and edit them. user_id links a login later (NULL for now).
CREATE TABLE athletes
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    account_id INTEGER NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    slug VARCHAR(60) NOT NULL,
    user_id INTEGER NULL,
    created_epoch BIGINT NOT NULL,
    created_by INTEGER NULL,
    CONSTRAINT fk_athletes_accounts FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_athletes_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_athletes_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);
CREATE UNIQUE INDEX ux_athletes_uid ON athletes (uid);
CREATE UNIQUE INDEX ux_athletes_slug ON athletes (slug);
CREATE INDEX ix_athletes_account ON athletes (account_id, display_name);

-- wristbands: one BLE beacon, identified by its BLE address (band_mac, 12 upper case hex). Belongs
-- to the account that enrolled it. status: active | lost | retired.
CREATE TABLE wristbands
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    band_mac CHAR(12) NOT NULL,
    label VARCHAR(40) NULL,
    status VARCHAR(8) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'lost', 'retired')),
    account_id INTEGER NOT NULL,
    created_epoch BIGINT NOT NULL,
    created_by INTEGER NULL,
    CONSTRAINT fk_wristbands_accounts FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_wristbands_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);
CREATE UNIQUE INDEX ux_wristbands_uid ON wristbands (uid);
CREATE UNIQUE INDEX ux_wristbands_band_mac ON wristbands (band_mac);
CREATE INDEX ix_wristbands_account ON wristbands (account_id);

-- Who has which band. expires_epoch NULL = permanent, else a loaner. closed_epoch set when the band
-- is returned, lost, retired or reassigned after its loan ran out. At most one open assignment per
-- band; an athlete may hold several bands.
CREATE TABLE wristband_assignments
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wristband_id INTEGER NOT NULL,
    athlete_id INTEGER NOT NULL,
    start_epoch BIGINT NOT NULL,
    expires_epoch BIGINT NULL,
    closed_epoch BIGINT NULL,
    closed_reason VARCHAR(12) NULL CHECK (closed_reason IN ('returned', 'lost', 'retired', 'expired')),
    assigned_by INTEGER NULL,
    CONSTRAINT fk_wristband_assignments_wristbands FOREIGN KEY (wristband_id) REFERENCES wristbands (id),
    CONSTRAINT fk_wristband_assignments_athletes FOREIGN KEY (athlete_id) REFERENCES athletes (id),
    CONSTRAINT fk_wristband_assignments_users FOREIGN KEY (assigned_by) REFERENCES users (id)
);
CREATE UNIQUE INDEX ux_wristband_assignments_open ON wristband_assignments (wristband_id) WHERE closed_epoch IS NULL;
CREATE INDEX ix_wristband_assignments_athlete ON wristband_assignments (athlete_id, start_epoch);

-- Every band presented to a controller or account pod (dev/{guid}/event, "band"). outcome is how
-- the band resolved at that moment: checked_in | unknown | unassigned | expired | lost | retired,
-- or enrolled (an account pod enrolled it from this presentation).
-- On a controller the newest row without checked_out_epoch is the athlete checked in at that
-- station; a new band or Check out closes it.
CREATE TABLE band_presentations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NOT NULL,
    band_mac CHAR(12) NOT NULL,
    wristband_id INTEGER NULL,
    athlete_id INTEGER NULL,
    outcome VARCHAR(12) NOT NULL,
    rssi INTEGER NULL,
    epoch BIGINT NOT NULL,
    checked_out_epoch BIGINT NULL,
    CONSTRAINT fk_band_presentations_devices FOREIGN KEY (device_id) REFERENCES devices (id),
    CONSTRAINT fk_band_presentations_wristbands FOREIGN KEY (wristband_id) REFERENCES wristbands (id),
    CONSTRAINT fk_band_presentations_athletes FOREIGN KEY (athlete_id) REFERENCES athletes (id)
);
CREATE INDEX ix_band_presentations_device ON band_presentations (device_id, id);
CREATE INDEX ix_band_presentations_athlete ON band_presentations (athlete_id, epoch) WHERE athlete_id IS NOT NULL;
CREATE INDEX ix_band_presentations_band ON band_presentations (band_mac, epoch);

-- New permission bit 12, manage_athletes (permissions.js). Grants that hold every earlier bit
-- (0..11, 4095) are full access grants, account admins in practice, so they get it too; anyone
-- else is granted it by an admin. Invites not yet accepted carry bits the same way.
UPDATE grants SET permission_bits = permission_bits | 4096 WHERE (permission_bits & 4095) = 4095;
UPDATE invites SET permission_bits = permission_bits | 4096 WHERE (permission_bits & 4095) = 4095;
