-- Support requests, second version (DECISIONS.md "Support requests"): severity, a reference number,
-- the location it was sent from, browser details, attachments, and a record of who was emailed.
--
-- ref: the number people see, YYYYMMDD-HHMMSS in UTC from the creation time; never the id (the id
--      reveals how many requests exist). New requests retry the next second on a clash.
-- severity: production-down | urgent | issue | feature-request.
-- subject: no longer written for new requests (the email subject is built when sent); kept for
--          requests made before this migration.
-- status stays open | waiting | closed; waiting is shown as "Answered".
ALTER TABLE support_requests ADD COLUMN ref VARCHAR(15) NULL;
ALTER TABLE support_requests ADD COLUMN severity VARCHAR(20) NOT NULL DEFAULT 'issue'
    CHECK (severity IN ('production-down', 'urgent', 'issue', 'feature-request'));
ALTER TABLE support_requests ADD COLUMN location_id INTEGER NULL;
ALTER TABLE support_requests ADD COLUMN user_agent VARCHAR(512) NULL;
ALTER TABLE support_requests ADD COLUMN viewport VARCHAR(20) NULL;
ALTER TABLE support_requests ADD COLUMN request_id VARCHAR(16) NULL;       -- req.id of the submit, for the event log
ALTER TABLE support_requests ADD COLUMN email_sent BOOLEAN NOT NULL DEFAULT false;   -- the SUPPORT_EMAILS message went out
ALTER TABLE support_requests ADD COLUMN closed_by INTEGER NULL;
ALTER TABLE support_requests ALTER COLUMN subject DROP NOT NULL;
ALTER TABLE support_requests ADD CONSTRAINT fk_support_requests_locations FOREIGN KEY (location_id) REFERENCES locations (id);
ALTER TABLE support_requests ADD CONSTRAINT fk_support_requests_closed_by FOREIGN KEY (closed_by) REFERENCES users (id);

-- Refs for existing requests: in creation order, each takes its creation second, or one second after
-- the previous ref when that second is already taken, so every ref is unique.
WITH RECURSIVE o AS
(
    SELECT id, created_epoch, ROW_NUMBER() OVER (ORDER BY created_epoch, id) AS rn
    FROM support_requests
),
a AS
(
    SELECT rn, id, created_epoch AS e FROM o WHERE rn = 1
    UNION ALL
    SELECT o.rn, o.id, GREATEST(o.created_epoch, a.e + 1) FROM a JOIN o ON o.rn = a.rn + 1
)
UPDATE support_requests s
SET ref = to_char(to_timestamp(a.e) AT TIME ZONE 'UTC', 'YYYYMMDD-HH24MISS')
FROM a
WHERE a.id = s.id;

ALTER TABLE support_requests ALTER COLUMN ref SET NOT NULL;
CREATE UNIQUE INDEX ux_support_requests_ref ON support_requests (ref);
CREATE INDEX ix_support_requests_account ON support_requests (account_id, status, updated_epoch);
CREATE INDEX ix_support_requests_location ON support_requests (location_id, status, updated_epoch);

-- One optional file and one screenshot per request, kept in the database (backed up with it).
-- content_type comes from the extension allowlist in services/support.js, never from the browser.
CREATE TABLE support_attachments
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL,
    filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes INTEGER NOT NULL,
    data BYTEA NOT NULL,
    created_epoch BIGINT NOT NULL,
    CONSTRAINT fk_support_attachments_requests FOREIGN KEY (request_id) REFERENCES support_requests (id)
);
CREATE INDEX ix_support_attachments_request ON support_attachments (request_id);

-- Who each support email went to: one row per address per send, because notifications.address
-- holds 254 characters and cuts a long To list.
--   message_id: the reply that was sent (NULL = the original request)
--   audience:   support (SUPPORT_EMAILS) | handlers (handle_support holders) | requester
--   notification_id: the notifications row for that send; no foreign key because notifications are
--                    purged after a year (jobs/tasks/purge.js) and support requests are kept.
CREATE TABLE support_recipients
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL,
    message_id INTEGER NULL,
    audience VARCHAR(10) NOT NULL CHECK (audience IN ('support', 'handlers', 'requester')),
    address VARCHAR(254) NOT NULL,
    user_id INTEGER NULL,
    outcome VARCHAR(10) NOT NULL CHECK (outcome IN ('sent', 'failed')),
    notification_id BIGINT NULL,
    created_epoch BIGINT NOT NULL,
    CONSTRAINT fk_support_recipients_requests FOREIGN KEY (request_id) REFERENCES support_requests (id),
    CONSTRAINT fk_support_recipients_messages FOREIGN KEY (message_id) REFERENCES support_messages (id),
    CONSTRAINT fk_support_recipients_users FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX ix_support_recipients_request ON support_recipients (request_id, id);
