-- Support requests, rebuilt to the support-request skill (DECISIONS.md "Support requests", Oct 2026).
-- Replaces the tables from 0003, 0008 and 0009, which never held a request (Jeff, Oct 2026); 0009
-- stays as it was committed because it may already be applied. The guard stops this migration, and
-- so the deploy, if any request exists, rather than delete it.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM support_requests) THEN
        RAISE EXCEPTION '0010: support_requests has rows; this migration replaces the support tables and would delete them';
    END IF;
END
$$;
DROP TABLE support_recipients;
DROP TABLE support_attachments;
DROP TABLE support_messages;
DROP TABLE support_requests;

-- One request. uid is the URL id; ref is the number people see, YYYYMMDD-HHMMSS in UTC (never the
-- id, which reveals how many requests exist); on a clash the next second is tried.
--   severity: production-down | urgent | issue | feature-request
--   status:   open (waiting on support) | answered (support replied) | closed
--   page_url: the path the request was sent from, on this site (one leading "/", no host)
--   request_id: req.id of the submit, to find it in the event log
--   email_sent: the SUPPORT_EMAILS message went out
CREATE TABLE support_requests
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL DEFAULT gen_random_uuid(),
    ref VARCHAR(15) NOT NULL,
    user_id INTEGER NOT NULL,
    account_id INTEGER NULL,
    location_id INTEGER NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'issue' CHECK (severity IN ('production-down', 'urgent', 'issue', 'feature-request')),
    status VARCHAR(10) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'answered', 'closed')),
    description VARCHAR(4000) NOT NULL,
    page_url VARCHAR(2048) NULL,
    page_title VARCHAR(200) NULL,
    user_agent VARCHAR(512) NULL,
    viewport VARCHAR(20) NULL,
    request_id VARCHAR(16) NULL,
    email_sent BOOLEAN NOT NULL DEFAULT false,
    created_epoch BIGINT NOT NULL,
    updated_epoch BIGINT NOT NULL,
    closed_epoch BIGINT NULL,
    closed_by INTEGER NULL,
    CONSTRAINT fk_support_requests_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_support_requests_accounts FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_support_requests_locations FOREIGN KEY (location_id) REFERENCES locations (id),
    CONSTRAINT fk_support_requests_closed_by FOREIGN KEY (closed_by) REFERENCES users (id)
);
CREATE UNIQUE INDEX ux_support_requests_uid ON support_requests (uid);
CREATE UNIQUE INDEX ux_support_requests_ref ON support_requests (ref);
CREATE INDEX ix_support_requests_status ON support_requests (status, updated_epoch);
CREATE INDEX ix_support_requests_user ON support_requests (user_id, created_epoch);
CREATE INDEX ix_support_requests_account ON support_requests (account_id, status, updated_epoch);
CREATE INDEX ix_support_requests_location ON support_requests (location_id, status, updated_epoch);

-- The reply thread. is_staff: written by support (a superadmin or handle_support holder) on someone
-- else's request; a support person replying on their own request writes as the requester.
CREATE TABLE support_messages
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_request_id INTEGER NOT NULL,
    author_id INTEGER NOT NULL,
    is_staff BOOLEAN NOT NULL,
    body VARCHAR(4000) NOT NULL,
    created_epoch BIGINT NOT NULL,
    CONSTRAINT fk_support_messages_requests FOREIGN KEY (support_request_id) REFERENCES support_requests (id),
    CONSTRAINT fk_support_messages_users FOREIGN KEY (author_id) REFERENCES users (id)
);
CREATE INDEX ix_support_messages_request ON support_messages (support_request_id, id);

-- The optional file and the screenshot, kept in the database (backed up with it).
-- content_type comes from the extension allowlist in services/support.js, never from the browser.
CREATE TABLE support_attachments
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_request_id INTEGER NOT NULL,
    filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes INTEGER NOT NULL,
    data BYTEA NOT NULL,
    created_epoch BIGINT NOT NULL,
    CONSTRAINT fk_support_attachments_requests FOREIGN KEY (support_request_id) REFERENCES support_requests (id)
);
CREATE INDEX ix_support_attachments_request ON support_attachments (support_request_id);

-- Who each support email went to: one row per address per send, because notifications.address
-- holds 254 characters and cuts a long To list.
--   support_message_id: the reply that was sent (NULL = the original request)
--   audience: support (SUPPORT_EMAILS) | handlers (handle_support holders) | requester
--   notification_id: the notifications row for that send; no foreign key because notifications are
--                    purged after a year (jobs/tasks/purge.js) and support requests are kept.
CREATE TABLE support_recipients
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_request_id INTEGER NOT NULL,
    support_message_id INTEGER NULL,
    audience VARCHAR(10) NOT NULL CHECK (audience IN ('support', 'handlers', 'requester')),
    address VARCHAR(254) NOT NULL,
    user_id INTEGER NULL,
    outcome VARCHAR(10) NOT NULL CHECK (outcome IN ('sent', 'failed')),
    notification_id BIGINT NULL,
    created_epoch BIGINT NOT NULL,
    CONSTRAINT fk_support_recipients_requests FOREIGN KEY (support_request_id) REFERENCES support_requests (id),
    CONSTRAINT fk_support_recipients_messages FOREIGN KEY (support_message_id) REFERENCES support_messages (id),
    CONSTRAINT fk_support_recipients_users FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX ix_support_recipients_request ON support_recipients (support_request_id, id);
