-- Chart email sent from the site (DECISIONS.md "Chart email from the site"). One row per send:
-- who sent which chart to whom, so sends are counted per user (the daily limit, the Chart emails
-- reports) and can be reviewed. The message itself is a notifications row (kind chart_email).
-- sensor_ids: the sensors in the attached data, for report scoping.
CREATE TABLE chart_emails
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epoch BIGINT NOT NULL,
    user_id INTEGER NOT NULL,
    account_id INTEGER NOT NULL,
    source VARCHAR(6) NOT NULL CHECK (source IN ('sensor', 'chart')),
    sensor_id INTEGER NULL,
    chart_id INTEGER NULL,
    sensor_ids INTEGER[] NOT NULL,
    from_epoch BIGINT NOT NULL,
    to_epoch BIGINT NOT NULL,
    recipients TEXT NOT NULL,
    recipient_count SMALLINT NOT NULL,
    subject VARCHAR(200) NOT NULL,
    comment TEXT NULL,
    format VARCHAR(8) NOT NULL,
    reading_count INTEGER NOT NULL,
    notification_id BIGINT NULL,
    outcome VARCHAR(10) NOT NULL CHECK (outcome IN ('sent', 'failed')),
    reason VARCHAR(200) NULL
);
CREATE INDEX ix_chart_emails_user_epoch ON chart_emails (user_id, epoch);
CREATE INDEX ix_chart_emails_account_epoch ON chart_emails (account_id, epoch);

-- A user's own daily limit: NULL uses the CHART_EMAIL_DAILY_LIMIT site setting. Raised on request
-- (a support request) by a superadmin.
ALTER TABLE users ADD COLUMN chart_email_daily_limit INTEGER NULL CHECK (chart_email_daily_limit >= 0);
